package main.java.view;

import javax.swing.*;
import java.awt.*;

public class ProfessorWelcomeUI {
    private JLabel inputQuiz;
    private JTextField quizTitle;
    private JPanel welcomeProfessorPanel;
    private JButton createQuiz;

    public JLabel getInputQuiz() {
        return inputQuiz;
    }

    public void setInputQuiz(JLabel inputQuiz) {
        this.inputQuiz = inputQuiz;
    }

    public JTextField getQuizTitle() {
        return quizTitle;
    }

    public void setQuizTitle(JTextField quizTitle) {
        this.quizTitle = quizTitle;
    }

    public JPanel getWelcomeProfessorPanel() {
        return welcomeProfessorPanel;
    }

    public void setWelcomeProfessorPanel(JPanel welcomeProfessorPanel) {
        this.welcomeProfessorPanel = welcomeProfessorPanel;
    }

    public JButton getCreateQuiz() {
        return createQuiz;
    }

    public void setCreateQuiz(JButton createQuiz) {
        this.createQuiz = createQuiz;
    }

    public void invalidateElements() {
        quizTitle.setText("");
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        welcomeProfessorPanel = new JPanel();
        welcomeProfessorPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        welcomeProfessorPanel.setBorder(BorderFactory.createTitledBorder("Welcome Professor"));
        inputQuiz = new JLabel();
        inputQuiz.setText("Enter Quiz Title");
        welcomeProfessorPanel.add(inputQuiz, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        quizTitle = new JTextField();
        quizTitle.setText("");
        welcomeProfessorPanel.add(quizTitle, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(150, -1), null, 0, false));
        createQuiz = new JButton();
        createQuiz.setText("Create Quiz");
        welcomeProfessorPanel.add(createQuiz, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return welcomeProfessorPanel;
    }
}
